:gen:
 :time_lapse: 3.months
 :database_name: 'pmu.db'
 :test_database_name: 'test.db'
 :default_date_time_format: '%d/%m/%Y %H:%M:%S.%L'
 :default_date_format: '%d/%m/%Y'
 :default_time_format: '%H:%M:%S.%L'
 :sql_create: 'sql.table_creation.yml'
 :sql_delete: 'sql.table_deletion.yml'
 :sql_insert: 'sql.insert.yml'
 :sql_select: 'sql.select.yml'
 :base_adress: 'file://D:/Dev/workspace/RPP/Test-HTML/accueil.htm'
 :base_adress_test: 'file:///D:/Dev/workspace/RPP/Test-HTML/accueil.htm'
 :base_adress_test_fetching: 'https://www.pmu.fr/turf/#20022014'

 